# permissions to do viewer databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-viewer-role
rules:
- apiGroups:
  - clarizen.cloud.clarizen.cloud
  resources:
  - databases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clarizen.cloud.clarizen.cloud
  resources:
  - databases/status
  verbs:
  - get
